### ISSUE TITLE
DRM content not playing on iOS 

### ISSUE THREAD

**Issue by shindevivek68** [bitmovin/bitmovin-player-ios-samples#10]
Hi Team, 

         
We have implemented DRM content playback on iOS.Currently, we are facing few issues on iOS while playing the content. Please find below link for DRM 

DRM content URL for safari : http://52.210.138.116

When we are playing above DRM content on safari Macbook which is working perfectly but while playing same configuration (using license URL, certificate URL, fairplayStreamUrl) it is not working on iOS. Please review below code for iOS.

         let certificateUrl = URL(fileURLWithPath: "cert.p12")

        guard let fairplayStreamUrl = URL(string: "https://yesflix.jetstream.video/hlsdrm/_definst_/smil:amazons3/jetstream.video/dev/1/Taipei.smil/playlist.m3u8"),
              let licenseUrl = URL(string: "http://fp.service.expressplay.com/hms/fp/rights/?ExpressPlayToken=AQALuGDeKeAAAABQcxeX6Zri6ab1OV8tHhvTb52NhSYPRB5ygz03NjiGrymyjsPQW-pQYjtoBDzAzBFSiy9F1JqRC3fBEV-Cb-Od7y65F3lJX4pvargqEa23oy9YTBNJD9JZUbpT0bMSuwGn2W0DHg") else {
            print("Please specify the needed resources marked with TODO in ViewController.swift file.")
            return
        }
        
        // Create player configuration
        let config = PlayerConfiguration()
        
        do {
            try config.setSourceItem(url: fairplayStreamUrl)
             //            let sourceItem = SourceItem(progressiveSource: ProgressiveSource(url: 
             fairplayStreamUrl))
            //            config.sourceItem = sourceItem
            //            config.styleConfiguration.userInterfaceType =  .bitmovin
            // create drm configuration
            let fpsConfig = FairplayConfiguration(license: licenseUrl, certificateURL: certificateUrl)

            // Example of how certificate data can be prepared if custom modifications are needed
            fpsConfig.prepareCertificate = { (data: Data) -> Data in
                // Do something with the loaded certificate
                return data
            }

            
            
            
            
            /**
             * Following callbacks are available to make custom modifications:
             * fpsConfig.prepareCertificate
             * fpsConfig.prepareLicense
             * fpsConfig.prepareContentId
             * fpsConfig.prepareMessage
             *
             * Custom request headers can be set using:
             * fpsConfig.certificateRequestHeaders
             * fpsConfig.licenseRequestHeaders
             *
             * See header documentation for more details!
             */

            config.sourceItem?.add(drmConfiguration: fpsConfig)
            
            // Create player based on player configuration
            let player = BitmovinPlayer(configuration: config)
            
            // Create player view and pass the player instance to it
            let playerView = BMPBitmovinPlayerView(player: player, frame: .zero)
            // Listen to player events
            player.add(listener: self)

            playerView.autoresizingMask = [.flexibleHeight, .flexibleWidth]
            playerView.frame = view.bounds
            
            view.addSubview(playerView)
            view.bringSubview(toFront: playerView)

            self.player = player

Let us know if anything is missing from my side.

**Comment by shindevivek68** [comment]
Hi Team, 

We tried below sample urls with above code which is working perfectly.

        let certificateUrl = URL(fileURLWithPath: "cert.p12")

        
        guard let fairplayStreamUrl = URL(string: "https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8"),
              let licenseUrl = URL(string: "https://widevine-proxy.appspot.com/proxy") else {
            print("Please specify the needed resources marked with TODO in ViewController.swift file.")
            return
        }


**Note: we are using expressplay service for genrating the licence url.**

**Comment by shindevivek68** [comment]
@matamegger @LudoMichaud @dweinber @sibe7691 @hawk23 Please look into this

**Comment by shindevivek68** [comment]
Thanks, @hawk23, Now it's working perfectly.

**Comment by shindevivek68** [comment]
Hi Team,
We are not able to cast DRM content using above code. PFA of error screen shot.

![img_0981](https://user-images.githubusercontent.com/43874076/49082054-bca42b00-f26e-11e8-9f4b-c49446ab8868.jpeg)


@hawk23  Kindly look into this as high priority.

**Comment by LudoMichaud** [comment]
Hi, @shindevivek68 
Thanks for reaching out. 
In order to play DRM protected content on cast device, you would have to provide a Widevine contrent as shown in our following code example : https://github.com/bitmovin/bitmovin-player-ios-samples/blob/master/AdvancedCasting/AdvancedCasting/ViewController.swift#L55

Please feel free to reach out to support@bitmovin.com in case you need any further help

**Comment by shindevivek68** [comment]
@hawk23  One more request can we store certificate on local project instade of storing on server side?

If Yes let us know the how can we configure FairplayConfiguration using local file. 

          let certificateUrl = URL(fileURLWithPath: "fairplay.cer")
