### ISSUE TITLE
DRM content not casting on TV

### ISSUE THREAD

**Issue by shindevivek68** [bitmovin/bitmovin-player-ios-samples#11]
Hi Team,
We are not able to cast DRM content using the above code. PFA of the error screenshot.

![img_0981](https://user-images.githubusercontent.com/43874076/49082054-bca42b00-f26e-11e8-9f4b-c49446ab8868.jpeg)

**Note: We are able to cast normal content on TV.**
@hawk23  Kindly look into this as high priority.

_Originally posted by @shindevivek68 in https://github.com/bitmovin/bitmovin-player-ios-samples/issues/10#issuecomment-442042558_

**Comment by hawk23** [comment]
Seems like you try to cast a FairPlay protected content. FairPlay DRM is not supported on Chromecast devices. As a solution, you'd need to define a different source which is used for casting by using the `RemoteControlConfiguration#prepareSource` callback. This source could then be for instance protected using Widevine. In this case, you need to add a `WidevineConfiguration` to the `SourceItem` which you return in the `prepareSource` callback.

See the [`AdvancedCasting`](https://github.com/bitmovin/bitmovin-player-ios-samples/blob/master/AdvancedCasting/AdvancedCasting/ViewController.swift) sample application for more information. There, a Widevine protected DASH stream is used when casting.

**Comment by shindevivek68** [comment]
Thanks, @hawk23 for a quick response.Now It's working.
