### ISSUE TITLE
Store certificate on Local directory 

### ISSUE THREAD

**Issue by shindevivek68** [bitmovin/bitmovin-player-ios-samples#13]
@hawk23  One more request can we store certificate on local project instade of storing on server side?

If Yes let us know the how can we configure FairplayConfiguration using local file. 

          let certificateUrl = URL(fileURLWithPath: "fairplay.cer")

_Originally posted by @shindevivek68 in https://github.com/bitmovin/bitmovin-player-ios-samples/issues/10#issuecomment-442777683_

**Comment by jarhoax** [comment]
Hi @shindevivek68,
thank you for reaching out. 
The requested feature is not available at the moment but will be included in the upcoming release.

**Comment by hawk23** [comment]
With today's release of iOS SDK `2.16.0`, it is possible to use file URLs for the FairPlay certificate.
