### ISSUE TITLE
Minimum bitrate download not working

### ISSUE THREAD

**Issue by amzadkhan68** [bitmovin/bitmovin-player-ios-samples#16]
We are downloading the DRM content with minimum bitrate 480000
`offlineManager.download(sourceItem: sourceItem, minimumBitrate: 480000)`

Download process runs twice, first it download the minimum bitrate content, then start with maximum bitrate content.  

Minimum bitrate progress ended but finish event not received,  Maximum bitrate progress start from starting, When maximum bitrate content process ended it finished with the finish event.

We are unable to download content with minimum bitrate.

**Comment by jarhoax** [comment]
This will be fixed in the upcoming release. We will get back at you then.

**Comment by jarhoax** [comment]
@amzadkhan68 This issue has been fixed in the `2.26.1` release.
