### ISSUE TITLE
BasicOfflinePlayback is not working

### ISSUE THREAD

**Issue by diehardest** [bitmovin/bitmovin-player-ios-samples#18]
I downloaded [BasicOfflinePlayback](https://github.com/bitmovin/bitmovin-player-ios-samples), added my license key to `Info.plist` and run `BasicOfflinePlayback`. 

When I am trying to download sample streams, nothing happens - UI stucks with "Downloading 0%", Cancel/Pause buttons do nothing, `OfflineManagerListener` callbacks are not calling. Xcode logs says there is some issue with null dictionary

<img width="1157" alt="Screen Shot 2019-05-14 at 17 37 12" src="https://user-images.githubusercontent.com/9250530/57706722-fa570d80-766e-11e9-8e00-cad99a00ec45.png">

**Comment by LudoMichaud** [comment]
Hi, 
Thanks for reaching out. 

Normally in case you try it out on a real device (not a simulator), it should work out of the boxas expected. 
Have you gave it a try ? 

In case you still have issues, please feel free to reach out to support@bitmovin.com. Our support team would then be happy to investigate if needed.
