### ISSUE TITLE
Using Framework UI to design iOS Framework

### ISSUE THREAD

**Issue by skyswitzerland** [bitmovin/bitmovin-player-ios-samples#19]
Hello,

I’m trying to understand how we can design our native bitmovin player using this : https://github.com/bitmovin/bitmovin-player-ui

So I took player-ui, I create custom button named ButtonSeekBar subclass of Button and I added it the player. I can see these button works when using gulp serve.

I added my custom button into demo factory. I also can see it , when selecting « buildDemoWithSeparate… »  when serving player ui.

So I did a gulp build-prod , I copied min.css and min.js file into CustomHtmlUI project. And I set it in swift as suggest in example by this way :
```
guard let cssURL = Bundle.main.url(forResource: "bitmovinplayer-ui.min", withExtension: "css"),
              let jsURL = Bundle.main.url(forResource: "bitmovinplayer-ui.min", withExtension: "js") else {
            print("Please specify the needed resources marked with TODO in ViewController.swift file.")
            return
        }
        config.styleConfiguration.playerUiCss = cssURL
        config.styleConfiguration.playerUiJs = jsURL
```

At the end, I didn’t see the player as it was in the web browser, it’s look like the « default one » 

One good thing , I did some css color change (to test) and I see it as well.

So the js didnt work in swift. But I didnt understand how the native code can choose which « sample » of the player to use, when serving with gulp, we have multiple profile and we choose one. How the native did the chose ?

I hope my question is clear.

Regards

**Comment by stonko1994** [comment]
The mobile SDKs builds the default small screen UI by calling the `buildDefaultSmallScreenUI` of the `UIFactory`. You find this within the `UIFactory` of the `bitmovin-player-ui`. So you would need to add your `ButtonSeekBar` to this `UIVariant` too, to work on our mobile SDKs.

**Comment by skyswitzerland** [comment]
thanks, it works by this way.
