### ISSUE TITLE
Audio tracks not visible in CustomHtmlUI Sample

### ISSUE THREAD

**Issue by skyswitzerland** [bitmovin/bitmovin-player-ios-samples#20]
Hello,
I'm making some tests using CustomHtmlUI Sample. When i put a steam with mutli audio tracks (like "sintel") i get audio track menu in the player-ui using gulp serve. But when using CustomHtmlUI Sample not, i can change the subtitles, but the menu for audio tracks is not visible. Do you know why ?
on iOS i use hls stream.

Thanks in advance

Regards

**Comment by jarhoax** [comment]
Hi,
thanks for reaching out.

The default stream in the `CustomHtmlUi` sample does not contain multiple audio tracks. 
Did you add the Sintel stream there?

**Comment by skyswitzerland** [comment]
yes i replace the stream by the "sintel" one.

**Comment by jarhoax** [comment]
Which UI version are you using?

**Comment by skyswitzerland** [comment]
modernUI

i did it by this way in uiFactory :
`export function buildDefaultSmallScreenUI(player: PlayerAPI, config: UIConfig = {}): UIManager {
    // return UIFactory.buildModernSmallScreenUI(player, config);
    return UIFactory.buildModernUI(player, config);
  }`

**Comment by jarhoax** [comment]
Ok, but which version of the Player UI are you using / forking?

**Comment by skyswitzerland** [comment]
hello @jarhoax , i'm using bitmovin-player-ui version "3.5.0"

**Comment by stonko1994** [comment]
This was fixed and released in `v2.29.0`
