### ISSUE TITLE
How to handle event between player-ui and native code

### ISSUE THREAD

**Issue by skyswitzerland** [bitmovin/bitmovin-player-ios-samples#21]
Hello,
i want to make a custom UI using player-ui, and i did it, i did a custom button with success.
Now i want to map it with my native code. Can you explain me how to do it ?

For example an Next Episode button, when i click on it , native code handle the event, and do custom native code.

Thanks in advance
regards

**Comment by jarhoax** [comment]
Hi, 

currently only calling the `PlayerAPI` is supported by the UI. There's no way at the moment to call your custom native code from the UI.

**Comment by skyswitzerland** [comment]
Hi,

Not 100% sure about that, as it was confirmed during our kick-off call by BitMovin that this behavior is possible . 

We talked about some Front end "custom button" that are linked to our app native code.

Is there any way to get such behavior ?

**Comment by skyswitzerland** [comment]
@jarhoax 
We also want to be able to communicate between from native code to PlayerUI.
For example, native app know when to show a button "skip intro", and then tell to the PlayerUI to show this button.
we can also imagine passing data to the PlayerUI (like metadata about when show which button) and then implement all the logic directly into the PlayerUI.

@jarhoax how js code is used into native app ? is it "translated" in native code, interpreted in js, then call when necessary native player api ?

**Comment by jarhoax** [comment]
@skyswitzerland Yes basically, the JS API calls are mapped to their native equivalent.

**Comment by jarhoax** [comment]
This has been implemented with Bitmovin SDK `2.28.0`. Closing.
