### ISSUE TITLE
License error

### ISSUE THREAD

**Issue by SikanderZeb** [bitmovin/bitmovin-player-ios-samples#22]
Hi,
  I downloaded the samples, changed the license key in info.plist, and tried to play the videos but the player is giving license error and asking to add the bundle identifier in player section of bitmovin dashboard which I have done multiple times.

 I tried changing bundle identifier multiple times and adding them to license, tried different license keys from different accounts, but still getting the error. Any idea?

**Comment by jarhoax** [comment]
Hi, I'm not experiencing this error. After adding a development team and a valid license key and making sure the bundle id is whitelisted in the according `Player --> Licenses` section, playback works fine. Can you double check again please? 

If you need further assistance, please share your license details with our support at support@bitmovin.com.

**Comment by SikanderZeb** [comment]
I tried with a new account and assumed the free trial would be enabled by default, which wasn't. Even though I added the bundle id to license, it wasn't working.

  After activating the free trial it worked. Thanks
