### ISSUE TITLE
Not able to play after download

### ISSUE THREAD

**Issue by iwonderdev** [bitmovin/bitmovin-player-ios-samples#23]
We are downloading AES-128 encrypted content which is working as expected. Issue is once we download the content it is not working in offline mode. When we load the bitmovin player in offline mode player requires internet connection to download encryption key and after that content works fine in offline mode. 

`offlineManager.createOfflineSourceItem(for: sourceItem, restrictedToAssetCache: true)`

Also facing same issue while downloading same encrypted content in the [offline content sample app](https://github.com/bitmovin/bitmovin-player-ios-samples/tree/master/BasicOfflinePlayback).

How to load encryption key without internet connection with bitmovin player?

**Comment by fhugoduarte** [comment]
I've the same problem! Do you have any solution?

**Comment by jarhoax** [comment]
Hello,

offline playback of AES-128 encrypted content is not yet supported with our SDK. For offline playback, only FairPlay HLS is supported currently.

We will let you know, once this gets addressed though.

**Comment by jpdemagalhaes** [comment]
@jarhoax do you guys have any plans to address this soon?

Because on Android it already supports offline playback of AES-128 encrypted content, only on iOS we're having this problem, which after researching a ton, AVPlayer already has support and you guys use it on your SDK, so it doesn't seem too far off from implementing it.

As you can see here:
https://assist-software.net/snippets/how-play-encrypted-http-live-streams-offline-avfoundation-ios-using-swift-4

**Comment by jarhoax** [comment]
Hi @jpdemagalhaes!

AVPlayer does not really support this, as you would have to trick the resourceloader to let you store the key. 

Please contact our support at support@bitmovin.com for those kind of questions resp. feature requests. We cannot tell atm when this is going to be addressed.

**Comment by fhugoduarte** [comment]
Hello @jarhoax, I'm not a native developer, but do you think it would be possible to implement this solution using bitmovin? 

I'm still looking for a workaround... 😅

**Comment by jarhoax** [comment]
Hello @fhugoduarte!

To implement this you would need access to the `AVPlayer` instance resp. the `AVAssetResourceLoader`. So we would need to implement this in the SDK directly (and there are plans for it, but not scheduled yet). I'm afraid, there is no proper way to workaround this atm.
