### ISSUE TITLE
Bug in SDK when using Playlist Example

### ISSUE THREAD

**Issue by thomasstevens89** [bitmovin/bitmovin-player-ios-samples#25]
The player seems to only want to fire just one `PlaybackFinishedEvent` during its lifetime, so the example code provided for Playlists doesn't actually work if you have more than 2 playlist items.

In order to get the example to work, I had to deinit and reinitialize the player as part of `playNextItem()`

**Comment by jarhoax** [comment]
That's intended (one playback finished event per playback session). We are currently working on a dedicated playlist API for our player which will address this request (and many more). Targeted release date is March 2021.
