### ISSUE TITLE
Intercept ad click event

### ISSUE THREAD

**Issue by buscarini** [bitmovin/bitmovin-player-ios-samples#27]
I've seen that the player listener has a function "onAdClicked", but is there a way to prevent the default action? I would like to present the clickThroughUrl modally in the app, instead of redirecting to the Browser.

**Comment by jarhoax** [comment]
We do not support an API on the player (yet) to change the target of the `clickThroughUrl`. Please file a support case [here](https://bitmovin.com/dashboard/support/cases/create) if still needed.
