### ISSUE TITLE
Translations for ad buttons

### ISSUE THREAD

**Issue by buscarini** [bitmovin/bitmovin-player-ios-samples#28]
Is there a way to translate the ad buttons? I mean the "Learn more" and the "Skip" labels. I've checked the documentation but I'm unable to find a way to do this.

**Comment by jarhoax** [comment]
As we are using the IMA SDK this UI is directly provided by it. We do not support an API on the player (yet) to customize them.

**Comment by stonko1994** [comment]
Additional information:

With version [2.57.0](https://bitmovin.com/docs/player/releases/ios/ios-2-57-0) we added the [`beforeInitialization`](https://cdn.bitmovin.com/player/ios/2/docs/Classes/BMPAdvertisingConfiguration.html#/c:objc(cs)BMPAdvertisingConfiguration(py)beforeInitialization) callback to the `AdvertisingConfiguration` which provides access to the `IMASettings`.

There you can set the `language` which will be used for the UI. [IMA Docu](https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/reference/Classes/IMASettings#language)
