### ISSUE TITLE
Basic casting example fails

### ISSUE THREAD

**Issue by bjimenezned** [bitmovin/bitmovin-player-ios-samples#3]
I'm trying the basic and advanced casting examples without any modifications to the source code (only adding the key and changing the id) the advanced casting works well but the basic casting does not work, chromecast recieves the video metadata but after a while it shows: 

`undefined. Exception: code 4, mediaError: MEDIA_ERR_SRC_NOT_SUPPORTED, message: DEMUXER_ERROR_COULD_NOT_OPEN`

**Comment by jarhoax** [comment]
Excuse my delayed response, I'm currently out of office. I will start investigating this issue on thursday and will come back to you then.

**Comment by jarhoax** [comment]
Thanks for reporting this issue. There is a problem with serializing the `SourceItem` to be handled by our latest Chromecast player. This will be addressed in one of the upcoming SDK releases. 

You will be notified as soon as this issue is fixed.

**Comment by jarhoax** [comment]
This issue is fixed with SDK version 2.12.0. 
The samples repository was updated accordingly so you should be able to run both samples without problems now.
