### ISSUE TITLE
How to download and change video with quality option? 

### ISSUE THREAD

**Issue by temchannat** [bitmovin/bitmovin-player-ios-samples#30]
Hello everyone, 
I have a problem on iOS download video with quality options. It takes a lot of time to download HLS video source since we don't have a way to select video quality when we download. There is a **BMPVideoQuality**, but I am not sure how to use it.  I have tried to find the sample but I could not find one.

**Comment by jarhoax** [comment]
Currently there is no way to select a dedicated video quality for offline playback. You can however set the [`minimumBitrate`](https://cdn.bitmovin.com/player/ios/2/docs/Classes/BMPDownloadConfiguration.html#/c:objc(cs)BMPDownloadConfiguration(py)minimumBitrate) to exclude non-matching bitrates.
