### ISSUE TITLE
Having issues with Fairplay when playing videos offline.

### ISSUE THREAD

**Issue by anand-pl** [bitmovin/bitmovin-player-ios-samples#31]
When a video is downloaded to a device and via an app then the the app is quit and then re-opened and if user tries to play video offline, we get the error:

`finished with error [-1009] Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x282a9def0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://licensing.bitmovin.com/licensing, NSErrorFailingURLKey=https://licensing.bitmovin.com/licensing, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}`

The first time a video is downloaded, it works fine offline.This issue is seen when the user quits the app and re-opens.

Seeing the issue on the bitmovin sample as well.

**Comment by jarhoax** [comment]
If you're encountering this issue still, please file a support case at https://bitmovin.com/dashboard/support/cases/create.
