### ISSUE TITLE
Custom Subtitle View functionality missing?

### ISSUE THREAD

**Issue by kflip** [bitmovin/bitmovin-player-ios-samples#4]
Subtitles are not show when using a custom interface.
I had to set "styleConfiguration.isUiEnabled" to false to deactivate bitmovin's overlay.
This setting also deactivates the display of subtitles.

The android version has a CustomSubtitleView solution for this. Is there any way for iOS to have a custom UI and subtitles?

**Comment by jarhoax** [comment]
If you want to apply your own UI in combination with subtitles you can set the `usertInterfaceType` property for the `StyleConfiguration` to `BMPUserInterfaceType.subtitle`.

Please let me know if this suits your case.

**Comment by kflip** [comment]
It works with the following setting:
```config.styleConfiguration.isUiEnabled = true
config.styleConfiguration.userInterfaceType = .subtitle```

Thank you

**Comment by jarhoax** [comment]
Glad to hear. You're welcome.
