### ISSUE TITLE
How to do PIP in iOS 

### ISSUE THREAD

**Issue by shindevivek68** [bitmovin/bitmovin-player-ios-samples#6]
Hi Team, 

      We are working on iOS custom UI, How can we implement custom picture In Picture [PIP] feature.

**Comment by hawk23** [comment]
Are you using the `BitmovinPlayerView` with a custom web UI, or did you build an own custom native UI?

Basic directions for implementing PiP are described [here](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player)

**Comment by shindevivek68** [comment]
@hawk23  We build our own custom UI.
