### ISSUE TITLE
WebVTT Subtitles doesn't work.

### ISSUE THREAD

**Issue by sibe7691** [bitmovin/bitmovin-player-ios-samples#9]
I am trying to add subtitles to the source item currently being played.
The subtitles show up as selectable options in the player, but the text is not shown.

**Player version:**
`pod 'BitmovinPlayer', git: 'https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod.git', tag: '2.13.3'`

**Here's the JSON representation of the subtitles I am trying to add.**
**The first line should be displayed at 00:01:14 but it isn't showing.**
`{"en-US":"https://devcontentmedia.blob.core.windows.net/transcripts/2cf18bcd-1d92-4547-a0e6-1a7e62c2f32b.vtt","ja-JP":"https://devcontentmedia.blob.core.windows.net/transcripts/fd4d1792-d0e9-4ead-9709-b972356ab054.vtt","zh-Hans":"https://devcontentmedia.blob.core.windows.net/transcripts/7b57a4c4-a1fa-4630-8cc5-5e7dd7ebdf7a.vtt","Zh-Hant":"https://devcontentmedia.blob.core.windows.net/transcripts/71637549-9289-4602-ac03-f86784b7ff22.vtt"}`

**This is the way I am adding them to the source item.**
```
        for (key, value) in allSubtitleDicts {
            let locale = Locale(identifier: key)
            let languageName = locale.localizedString(forIdentifier: key) ?? "random"
            
            let subtitleTrack = SubtitleTrack(url: URL(string: value),
                                              label: languageName,
                                              identifier: key,
                                              isDefaultTrack: true,
                                              language: languageName)
            sourceItem?.add(subtitleTrack: subtitleTrack)
        }
```

**Comment by LudoMichaud** [comment]
Hi, 
thanks for reaching out. 
As mentioned in the thread we have together, your subtitles seems to be working as expected with our basic casting demo app (https://github.com/bitmovin/bitmovin-player-ios-samples/tree/master/BasicCasting). 

``` swift
            let subtitleTrack = SubtitleTrack(url: URL(string: "https://devcontentmedia.blob.core.windows.net/transcripts/2cf18bcd-1d92-4547-a0e6-1a7e62c2f32b.vtt"),
                                              label: "en",
                                              identifier: "en",
                                              isDefaultTrack: true,
                                              language: "en")
            config.sourceItem?.add(subtitleTrack: subtitleTrack)
```


Please let me know in case you have any further question. I'm happy to help

**Comment by shindevivek68** [comment]
@LudoMichaud We have verified subtitle on basic casting example still it's not working.

Note: We also tried in DRM content & on casting. please provide any solution for subtitle & audio track in iOS.

**Comment by adamszeptycki** [comment]
I don't know if that was solved or not, but I have problems making the subtitles work.
(in objective-c)

**Comment by jonathanm-tkf** [comment]
same here please put example in objectve c

thanks
